"""empty message

Revision ID: 5903f4bdc46e
Revises: 
Create Date: 2020-05-20 16:56:19.462095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5903f4bdc46e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=110), nullable=True))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
