"""empty message

Revision ID: d6dca199c09e
Revises: 5f990c33089a
Create Date: 2020-06-25 19:09:14.092584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dca199c09e'
down_revision = '5f990c33089a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_role_user',
    sa.Column('cmsrole_id', sa.Integer(), nullable=True),
    sa.Column('cmsuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cmsrole_id'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['cmsuser_id'], ['cms_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_role_user')
    op.drop_table('cms_role')
    # ### end Alembic commands ###
