"""empty message

Revision ID: f1c3d958bae2
Revises: 6b644db549e4
Create Date: 2020-05-15 23:44:23.914751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1c3d958bae2'
down_revision = '6b644db549e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=110), nullable=True))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=110), nullable=True))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
